repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [--line-length=100]
        language_version: python3
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, --in-place]